// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNzI-4n5ujqjQujK3BxxeNUDUaeSml6c',
    appId: '1:685901186377:android:9747c65141967421870698',
    messagingSenderId: '685901186377',
    projectId: 'momo-9bb17',
    databaseURL: 'https://momo-9bb17-default-rtdb.firebaseio.com',
    storageBucket: 'momo-9bb17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3fNc5oWCCYwDL3QZnSAN8AAuwQqT5yMA',
    appId: '1:685901186377:ios:9d8c0c8a45fe04aa870698',
    messagingSenderId: '685901186377',
    projectId: 'momo-9bb17',
    databaseURL: 'https://momo-9bb17-default-rtdb.firebaseio.com',
    storageBucket: 'momo-9bb17.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYV2exnpYree6qvfsutNxINXNGuYiow3Q',
    appId: '1:685901186377:web:2b8f6b54af4be8d7870698',
    messagingSenderId: '685901186377',
    projectId: 'momo-9bb17',
    authDomain: 'momo-9bb17.firebaseapp.com',
    databaseURL: 'https://momo-9bb17-default-rtdb.firebaseio.com',
    storageBucket: 'momo-9bb17.firebasestorage.app',
    measurementId: 'G-2VZ0BVWBYN',
  );

}