// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSnH8t36D1ymREPAumAztDMge2SSvSaNI',
    appId: '1:943824648877:android:44c611d25925498d136424',
    messagingSenderId: '943824648877',
    projectId: 'microsv-cba68',
    storageBucket: 'microsv-cba68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGR0w20-tVvnvIghk0JdU2Eb2cZIn8XmY',
    appId: '1:943824648877:ios:d65a818b73102094136424',
    messagingSenderId: '943824648877',
    projectId: 'microsv-cba68',
    storageBucket: 'microsv-cba68.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYV2exnpYree6qvfsutNxINXNGuYiow3Q',
    appId: '1:685901186377:web:2b8f6b54af4be8d7870698',
    messagingSenderId: '685901186377',
    projectId: 'momo-9bb17',
    authDomain: 'momo-9bb17.firebaseapp.com',
    databaseURL: 'https://momo-9bb17-default-rtdb.firebaseio.com',
    storageBucket: 'momo-9bb17.firebasestorage.app',
    measurementId: 'G-2VZ0BVWBYN',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnO-moPvMMwkaPytZOS0BX5nJR_yRRMjo',
    appId: '1:943824648877:web:105e819c109a0ba3136424',
    messagingSenderId: '943824648877',
    projectId: 'microsv-cba68',
    authDomain: 'microsv-cba68.firebaseapp.com',
    storageBucket: 'microsv-cba68.firebasestorage.app',
  );

}